package com.everis.quotationrestservice.model;
// Generated 8/10/2019 12:07:39 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name = "servicio", catalog = "examenequipotres")
public class Servicio implements java.io.Serializable {

	private Integer idservicio;
	private String nombre;
	private Double costo;

	public Servicio() {
	}

	public Servicio(String nombre, Double costo) {
		this.nombre = nombre;
		this.costo = costo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idservicio", unique = true, nullable = false)
	public Integer getIdservicio() {
		return this.idservicio;
	}

	public void setIdservicio(Integer idservicio) {
		this.idservicio = idservicio;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "costo", precision = 22, scale = 0)
	public Double getCosto() {
		return this.costo;
	}

	public void setCosto(Double costo) {
		this.costo = costo;
	}

}
