-- MySQL Script generated by MySQL Workbench
-- Tue Oct  8 10:43:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema examen4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema examen4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `examenequipotres` DEFAULT CHARACTER SET utf8 ;
USE `examenequipotres` ;

-- -----------------------------------------------------
-- Table `examen4`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examenequipotres`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apaterno` VARCHAR(45) NULL,
  `amaterno` VARCHAR(45) NULL,
  `tipocliente` INT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `examen4`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examenequipotres`.`servicio` (
  `idservicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `costo` double  NULL,
  PRIMARY KEY (`idservicio`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
